data_distributor:
  local_dataset:
    train: data.csv
    test: null
    task: classification
    target_value: '10'
    sep: ','
  sampling:
    type: Non-IID
    non_iid_ness: 1
  result:
    train: data.csv
    test: null
